runtime: go122

app_engine_apis: true

handlers:
- url: /.*
  script: _go_app

automatic_scaling:
  min_instances: 0 # Latency is acceptable, so we can have 0 instances by default. We then have cold starts.
  max_instances: 2
  target_cpu_utilization: 0.9 # High latency is acceptable, so let's save some money
