name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.11
        
    - name: Dependencies
      run: go get google.golang.org/appengine/memcache
      
    - name: Pre build
      run: go mod init dummy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
