name: Go

on:
  push:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.mod'
  pull_request:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.mod'
  workflow_dispatch:

jobs:
  build: # Build and test the Go application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        
    - name: Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./cmd/liquipedia-calendar

    - name: Test
      run: go test -v ./...

  release: # Create release with binary
    # Only run on pushes to master branch (not PRs)
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    # Only run if the build job was successful
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Get version
      id: version
      run: |
        # Use calendar versioning: YYYY.MM.DD-commit
        VERSION="$(date -u +%Y.%m.%d)-$(git rev-parse --short HEAD)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build binary
      run: |
        go build -v -o liquipedia-calendar ./cmd/liquipedia-calendar

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        files: liquipedia-calendar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
